version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    depends_on:
      - app1
      - app2
      - app3
    ports:
      - "8080:80"
  db:
    build:
      context: .
      dockerfile: ./db.Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app1:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - "5001:3000"
    depends_on:
      - db
    
  app2:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - "5002:3000"
    depends_on:
      - db

  app3:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - "5003:3000"
    depends_on:
      - db
